# Importing and division of data:
#### Group 6

In [1]:
import numpy as np
from IPython.display import display,HTML
from numpy import *

np.set_printoptions(suppress=True)

from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))

#### Importing the data

Our data was imported using the numpy function ```genfromtxt('file.csv')``` which reads and converts ```.csv``` files into a single ```numpy array``` which will be useful for dividing and saving purposes.

In [2]:
### Importing some useful packages
#This ensures that plots appear in the sheet and not in a new window
%matplotlib inline 

#Pandas is an alternative numerical processing library like numpy: they have differences
#We will use Pandas only to provide a preview of the data once we've read it in
import pandas as pd


data = np.genfromtxt('online_shoppers_intention_selection.csv',delimiter=",")

#Convert the numpy array to a pandas DataFrame
#and display the first 10 rows as html
display(pd.DataFrame(data).head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,21.0,1079.0,4.0,176.0,67.0,2162.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,1.0,11.0,2.0,1.0,0.0
1,6.0,91.0,0.0,0.0,56.0,955.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,4.0,2.0,2.0,1.0,1.0
2,0.0,0.0,0.0,0.0,69.0,1002.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,4.0,2.0,2.0,0.0,0.0
3,8.0,212.0,3.0,124.0,52.0,968.0,0.0,0.0,214.0,0.0,11.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
4,0.0,0.0,0.0,0.0,20.0,301.0,0.0,0.0,0.0,0.0,5.0,3.0,2.0,1.0,3.0,2.0,0.0,0.0
5,3.0,143.0,2.0,29.0,3.0,380.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,4.0,3.0,0.0,0.0,0.0
6,6.0,158.0,1.0,430.0,146.0,5602.0,0.0,0.0,6.0,0.0,11.0,2.0,10.0,7.0,2.0,2.0,0.0,1.0
7,0.0,0.0,0.0,0.0,65.0,1803.0,0.0,0.0,0.0,0.0,5.0,3.0,2.0,6.0,3.0,2.0,0.0,0.0
8,0.0,0.0,0.0,0.0,16.0,381.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,1.0,2.0,2.0,0.0,0.0
9,4.0,75.0,0.0,0.0,10.0,158.0,0.0,0.0,20.0,0.0,10.0,1.0,1.0,3.0,2.0,2.0,1.0,1.0

#### Randomizing the data 

It is important to randomize ones data set before dividing the data into Training, Cross Validtion and Testing data sets. Thus we made use of the numpy function ```numpy.random.shuffle(arr)``` to shuffle our data by rows while leaving the contents of each row unshifted.

In [3]:
data2 =data
np.random.shuffle(data2)
data2
display(pd.DataFrame(data2).head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,5.0,1415.0,0.0,0.0,34.0,588.0,0.0,0.0,8.0,0.0,8.0,2.0,5.0,1.0,1.0,2.0,0.0,1.0
1,2.0,28.0,0.0,0.0,73.0,2260.0,0.0,0.0,0.0,0.0,6.0,2.0,2.0,7.0,4.0,2.0,1.0,0.0
2,6.0,149.0,3.0,267.0,120.0,3934.0,0.0,0.0,8.0,0.0,11.0,2.0,2.0,4.0,2.0,2.0,1.0,0.0
3,8.0,97.0,0.0,0.0,24.0,498.0,0.0,0.0,5.0,0.0,10.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
4,2.0,21.0,1.0,802.0,48.0,2073.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,3.0,2.0,2.0,1.0,0.0
5,4.0,24.0,0.0,0.0,29.0,749.0,0.0,0.0,0.0,0.0,11.0,1.0,1.0,3.0,2.0,2.0,0.0,1.0
6,0.0,0.0,0.0,0.0,20.0,1117.0,0.0,0.0,0.0,0.0,3.0,2.0,4.0,7.0,2.0,2.0,0.0,0.0
7,1.0,75.0,0.0,0.0,20.0,1173.0,0.0,0.0,21.0,0.0,11.0,3.0,2.0,8.0,11.0,2.0,0.0,1.0
8,2.0,6.0,0.0,0.0,9.0,89.0,0.0,0.0,0.0,0.0,9.0,1.0,1.0,4.0,4.0,2.0,1.0,1.0
9,4.0,206.0,0.0,0.0,9.0,113.0,0.0,0.0,0.0,0.0,10.0,2.0,2.0,1.0,6.0,2.0,0.0,0.0

#### Dividing the data

We have divided our origional data into 3 datasets which are namely, ```Training``` consisting of 60% of the origional data, ```Cross Validation``` consisting of 20% and ```Testing``` consisting of 20% of remaining origional data.

In [4]:
#sets the ratio of training data: validation data: testing data(currently 80:10:10)

perc1= int(0.6*len(data))
perc2= int(0.8*len(data))

train = data2[:perc1]
val = data2[perc1:perc2]
test = data2[perc2:]

In [5]:
print("\nTheres a total of "+(str)(len(data2))+ " records in this data set")

#Convert the numpy array to a pandas DataFrame
#and display the first 10 rows as html for each data set

print("\nTraining data: "+(str)(len(train)))
display(pd.DataFrame(train).head(10))
print("\nCV data: "+(str)(len(val)))
display(pd.DataFrame(val).head(10))
print("\nTesting data: "+(str)(len(test)))
display(pd.DataFrame(test).head(10))

Theres a total of 3816 records in this data set

Training data: 2289

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,5.0,1415.0,0.0,0.0,34.0,588.0,0.0,0.0,8.0,0.0,8.0,2.0,5.0,1.0,1.0,2.0,0.0,1.0
1,2.0,28.0,0.0,0.0,73.0,2260.0,0.0,0.0,0.0,0.0,6.0,2.0,2.0,7.0,4.0,2.0,1.0,0.0
2,6.0,149.0,3.0,267.0,120.0,3934.0,0.0,0.0,8.0,0.0,11.0,2.0,2.0,4.0,2.0,2.0,1.0,0.0
3,8.0,97.0,0.0,0.0,24.0,498.0,0.0,0.0,5.0,0.0,10.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
4,2.0,21.0,1.0,802.0,48.0,2073.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,3.0,2.0,2.0,1.0,0.0
5,4.0,24.0,0.0,0.0,29.0,749.0,0.0,0.0,0.0,0.0,11.0,1.0,1.0,3.0,2.0,2.0,0.0,1.0
6,0.0,0.0,0.0,0.0,20.0,1117.0,0.0,0.0,0.0,0.0,3.0,2.0,4.0,7.0,2.0,2.0,0.0,0.0
7,1.0,75.0,0.0,0.0,20.0,1173.0,0.0,0.0,21.0,0.0,11.0,3.0,2.0,8.0,11.0,2.0,0.0,1.0
8,2.0,6.0,0.0,0.0,9.0,89.0,0.0,0.0,0.0,0.0,9.0,1.0,1.0,4.0,4.0,2.0,1.0,1.0
9,4.0,206.0,0.0,0.0,9.0,113.0,0.0,0.0,0.0,0.0,10.0,2.0,2.0,1.0,6.0,2.0,0.0,0.0

CV data: 763

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,3.0,3.0,2.0,0.0,0.0
1,5.0,73.0,1.0,55.0,41.0,1705.0,0.0,0.0,7.0,0.0,5.0,2.0,4.0,2.0,2.0,2.0,0.0,0.0
2,14.0,160.0,6.0,1079.0,154.0,7405.0,0.0,0.0,8.0,0.0,11.0,4.0,1.0,4.0,1.0,2.0,0.0,1.0
3,8.0,203.0,0.0,0.0,116.0,3505.0,0.0,0.0,62.0,0.0,11.0,2.0,2.0,1.0,6.0,2.0,0.0,1.0
4,0.0,0.0,0.0,0.0,12.0,312.0,0.0,0.0,17.0,0.0,5.0,2.0,2.0,8.0,6.0,2.0,0.0,1.0
5,0.0,0.0,0.0,0.0,24.0,968.0,0.0,0.0,106.0,0.0,11.0,1.0,1.0,9.0,2.0,2.0,0.0,1.0
6,9.0,441.0,0.0,0.0,122.0,2577.0,0.0,0.0,75.0,0.0,11.0,1.0,1.0,1.0,2.0,2.0,0.0,1.0
7,3.0,68.0,1.0,103.0,10.0,808.0,0.0,0.0,35.0,0.0,3.0,2.0,2.0,3.0,7.0,2.0,1.0,1.0
8,2.0,561.0,2.0,31.0,95.0,4817.0,0.0,0.0,50.0,0.0,11.0,1.0,1.0,5.0,2.0,2.0,0.0,1.0
9,5.0,415.0,0.0,0.0,115.0,4424.0,0.0,0.0,13.0,0.0,8.0,2.0,4.0,4.0,1.0,2.0,1.0,1.0

Testing data: 764

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,2.0,17.0,0.0,0.0,11.0,440.0,0.0,0.0,54.0,0.0,5.0,2.0,4.0,8.0,4.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,5.0,164.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,1.0,3.0,2.0,1.0,0.0
2,0.0,0.0,0.0,0.0,2.0,64.0,0.0,0.0,0.0,0.0,11.0,3.0,2.0,8.0,2.0,2.0,0.0,0.0
3,0.0,0.0,2.0,6.0,1.0,25.0,0.0,0.0,0.0,1.0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,0.0
4,1.0,4.0,0.0,0.0,49.0,4651.0,0.0,0.0,0.0,0.0,5.0,2.0,2.0,7.0,2.0,2.0,0.0,0.0
5,9.0,103.0,0.0,0.0,16.0,172.0,0.0,0.0,0.0,0.0,10.0,1.0,1.0,1.0,2.0,2.0,0.0,1.0
6,4.0,61.0,0.0,0.0,16.0,502.0,0.0,0.0,71.0,0.0,5.0,4.0,1.0,2.0,3.0,2.0,1.0,1.0
7,6.0,352.0,0.0,0.0,11.0,605.0,0.0,0.0,0.0,0.0,6.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
8,0.0,0.0,0.0,0.0,7.0,93.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
9,0.0,0.0,0.0,0.0,2.0,150.0,0.0,0.0,0.0,0.0,10.0,2.0,2.0,3.0,5.0,2.0,0.0,0.0

#### Saving the datasets

We then had to save our datasets into their respective ```.dat``` files, which was made possible through the use of the function ```savetxt('file.dat')```

In [6]:
#writes the arrays into their respective files
savetxt('group6_train.dat', train)
savetxt('group6_cv.dat', val)
savetxt('group6_test.dat', test)

#### Hint

When loading the datasets make use of the function ```loadtxt('file.dat')``` as illustrated below.

In [7]:
c = loadtxt('group6_train.dat')
display(pd.DataFrame(c).head(10))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,5.0,1415.0,0.0,0.0,34.0,588.0,0.0,0.0,8.0,0.0,8.0,2.0,5.0,1.0,1.0,2.0,0.0,1.0
1,2.0,28.0,0.0,0.0,73.0,2260.0,0.0,0.0,0.0,0.0,6.0,2.0,2.0,7.0,4.0,2.0,1.0,0.0
2,6.0,149.0,3.0,267.0,120.0,3934.0,0.0,0.0,8.0,0.0,11.0,2.0,2.0,4.0,2.0,2.0,1.0,0.0
3,8.0,97.0,0.0,0.0,24.0,498.0,0.0,0.0,5.0,0.0,10.0,2.0,2.0,1.0,2.0,2.0,0.0,1.0
4,2.0,21.0,1.0,802.0,48.0,2073.0,0.0,0.0,0.0,0.0,11.0,2.0,2.0,3.0,2.0,2.0,1.0,0.0
5,4.0,24.0,0.0,0.0,29.0,749.0,0.0,0.0,0.0,0.0,11.0,1.0,1.0,3.0,2.0,2.0,0.0,1.0
6,0.0,0.0,0.0,0.0,20.0,1117.0,0.0,0.0,0.0,0.0,3.0,2.0,4.0,7.0,2.0,2.0,0.0,0.0
7,1.0,75.0,0.0,0.0,20.0,1173.0,0.0,0.0,21.0,0.0,11.0,3.0,2.0,8.0,11.0,2.0,0.0,1.0
8,2.0,6.0,0.0,0.0,9.0,89.0,0.0,0.0,0.0,0.0,9.0,1.0,1.0,4.0,4.0,2.0,1.0,1.0
9,4.0,206.0,0.0,0.0,9.0,113.0,0.0,0.0,0.0,0.0,10.0,2.0,2.0,1.0,6.0,2.0,0.0,0.0